In [3]:
# Coursera Depp learning specialization 첫 강의 리뷰겸 만들어보는 간단한 뉴럴넷

<h1>밑바닥부터 짜는 로지스틱 회귀</h1>
<h2>사용되는 수식들...</h2>
<ul>
    <li>Logistic regression : $\sigma(Z) = \sigma(W A + b)$</li>
    <li>Cost function : $$-\frac{1}{m} \sum\limits_{i = 1}^{m} (y^{(i)}\log\left(a^{[L] (i)}\right) + (1-y^{(i)})\log\left(1- a^{[L](i)}\right))$$</li>
    <li>
        <h2>Backward propagation</h2>
        <ul>
            <li>$$ dW^{[l]} = \frac{\partial \mathcal{J} }{\partial W^{[l]}} = \frac{1}{m} dZ^{[l]} A^{[l-1] T}$$</li>
            <li>$$ db^{[l]} = \frac{\partial \mathcal{J} }{\partial b^{[l]}} = \frac{1}{m} \sum_{i = 1}^{m} dZ^{[l](i)}$$</li>
            <li>$$ dA^{[l-1]} = \frac{\partial \mathcal{L} }{\partial A^{[l-1]}} = W^{[l] T} dZ^{[l]}$$</li>
        </ul>
    </li>
</ul>
<h2>Activation function</h2>
<ul>
    <li>Hidden layer : Relu</li>
    <li>Output layer : Sigmoid</li>
</ul>


<h3><a href="https://www.coursera.org/specializations/deep-learning?">Coursera 강의 실습 참조</a></h3>

In [2]:
import numpy as np
import tensorflow as tf

c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)


In [30]:
# Activation Functions
def relu(Z):
    cache = Z
    A = tf.nn.relu(Z)
    
    return A, cache


def sigmoid(Z):
    cache = Z
    A = tf.math.sigmoid(Z)
    
    return A, cache

In [66]:
# Init parameters
def initialize_parameters(layer_dims, alpha=0.01):
    # parameter layer_dims : Array of dimesions of layers.
    np.random.seed(1)
    L = len(layer_dims)
    
    print(L)
    
    # store paremters for each layer.
    parameters = {}
    
    # first layer is input layer.
    # last layer is output layer.
    for l in range (1, L):
        parameters["W" + str(l)] = np.random.randn(layer_dims[l], layer_dims[l - 1]) * alpha
        parameters["b" + str(l)] = np.zeros((layer_dims[l], 1))
        
        assert(parameters["W" + str(l)].shape == (layer_dims[l], layer_dims[l - 1]))
        assert(parameters["b" + str(l)].shape == (layer_dims[l], 1))
        
        
    return parameters

In [57]:
# Forward propagation
def forward(A, W, b):    
    # Calculate Z value.
    Z = tf.tensordot(W.T, A, axes=1) + b
    
    cache = (A, W, b)
    
    return Z, cache
    
    
def forward_propagation(A_prev, W, b, activation="sigmoid"):
    Z, param_cache = forward(A_prev, W, b)
    if activation == "sigmoid":
        A, Z_cache = sigmoid(Z)
    elif activation == "relu":
        A, Z_cache = relu(Z)
        
    cache = (param_cache, Z_cache)
    
    return A, cache


def layered_forward_propagation(X, parameters):
    caches = []
    A = X
    L = len(parameters) // 2
    
    for l in range (1, L):
        A_prev = A
        A, cache = forward_propagation(A_prev, parameters["W" + str(l)], parameters["b" + str(l)], "relu")
        caches.append(cache)
        
        
    AL, cache = forward_propagation(A, parameters["W" + str(L)], parameters["b" + str(L)], "sigmoid")
    caches.append(cache)
    
    return AL, caches

In [62]:
X = np.random.randn(10, 1)
params = initialize_parameters([10, 10, 10])
layered_forward_propagation(X, params)

{'W1': array([[ 0.01624345, -0.00611756, -0.00528172, -0.01072969,  0.00865408,
        -0.02301539,  0.01744812, -0.00761207,  0.00319039, -0.0024937 ],
       [ 0.01462108, -0.02060141, -0.00322417, -0.00384054,  0.01133769,
        -0.01099891, -0.00172428, -0.00877858,  0.00042214,  0.00582815],
       [-0.01100619,  0.01144724,  0.00901591,  0.00502494,  0.00900856,
        -0.00683728, -0.0012289 , -0.00935769, -0.00267888,  0.00530355],
       [-0.00691661, -0.00396754, -0.00687173, -0.00845206, -0.00671246,
        -0.00012665, -0.0111731 ,  0.00234416,  0.01659802,  0.00742044],
       [-0.00191836, -0.00887629, -0.00747158,  0.01692455,  0.00050808,
        -0.00636996,  0.00190915,  0.02100255,  0.00120159,  0.00617203],
       [ 0.0030017 , -0.0035225 , -0.01142518, -0.00349343, -0.00208894,
         0.00586623,  0.00838983,  0.00931102,  0.00285587,  0.00885141],
       [-0.00754398,  0.01252868,  0.0051293 , -0.00298093,  0.00488518,
        -0.00075572,  0.01131629,  0.0

(<tf.Tensor: shape=(10, 1), dtype=float64, numpy=
 array([[0.49996254],
        [0.50002304],
        [0.50015402],
        [0.50021609],
        [0.49991345],
        [0.4999705 ],
        [0.50009549],
        [0.49989358],
        [0.49999173],
        [0.49997211]])>,
 [((array([[-0.40087819],
           [ 0.82400562],
           [-0.56230543],
           [ 1.95487808],
           [-1.33195167],
           [-1.76068856],
           [-1.65072127],
           [-0.89055558],
           [-1.1191154 ],
           [ 1.9560789 ]]),
    array([[ 0.01624345, -0.00611756, -0.00528172, -0.01072969,  0.00865408,
            -0.02301539,  0.01744812, -0.00761207,  0.00319039, -0.0024937 ],
           [ 0.01462108, -0.02060141, -0.00322417, -0.00384054,  0.01133769,
            -0.01099891, -0.00172428, -0.00877858,  0.00042214,  0.00582815],
           [-0.01100619,  0.01144724,  0.00901591,  0.00502494,  0.00900856,
            -0.00683728, -0.0012289 , -0.00935769, -0.00267888,  0.00530355],


In [101]:
def backward_relu(dA, cache):
    # parameter cache == Z_cache
    
    Z = cache
    dZ = np.array(dA)
    dZ[Z<=0] = 0
    
    return dZ


def backward_sigmoid(dA, cache):
    # parameter cache == Z_cache
    Z = cache
    
    y = tf.nn.sigmoid(Z)
    
    dZ = dA / (y * (1-y))
    
    return dZ
    
    
# Compute cost
def cost(AL, Y):
    # m == Number of train sets
    m = Y.shape[1]
    
    cost = -tf.reduce_sum(Y * tf.math.log(AL) + (1 - Y) * tf.math.log(1 - AL))
    
    cost = tf.squeeze(cost)
    
    return cost

In [99]:
# Backward propagation
def backward(dZ, cache):
    A_prev, W, b = cache
    m = A_prev.shape[1]
    
    dW = tf.tensordot(dZ, tf.transpose(A_prev), axes=1) / m
    db = tf.reduce_sum(dZ) / m
    dA_prev = tf.tensordot(W, dZ, axes=1)
    
    return dA_prev, dW, db


def backward_propagation(dA, cache, activation="sigmoid"):
    param_cache, Z_cache = cache
    if activation == "relu":
        dZ = backward_relu(dA, Z_cache)
        print("relu dZ: ", dZ)
 
    elif activation == "sigmoid":
        dZ = backward_sigmoid(dA, Z_cache)
        print("sigmoid dZ: ", dZ)
    
    dA_prev, dW, db = backward(dZ, param_cache)
    
    return dA_prev, dW, db


def layered_backward_propagation(AL, Y, caches):
    grads = {}    
    L = len(caches)
    m = AL.shape[1]
    Y = Y.reshape(AL.shape)
    
    dAL = -(tf.math.divide(Y, AL) - tf.math.divide(1 - Y, 1 - AL))
    
    current_cache = caches[L - 1]
    grads["dA" + str(L - 1)], grads["dW" + str(L)], grads["db" + str(L)] = backward_propagation(dAL, current_cache)
    
    for l in reversed(range(L-1)):
        current_cache = caches[l]
        grads["dA" + str(l)], grads["dW" + str(l + 1)], grads["db" + str(l + 1)] = backward_propagation(grads["dA" + str(l + 1)], current_cache)
        
    return grads


        

In [104]:
X = np.random.randn(10, 1)
params = initialize_parameters([10, 10, 10])
AL, caches = layered_forward_propagation(X, params)
#Y = np.array([[1.],
#              [1.], 
#              [1.],
#              [1.],
#              [1.],
#              [1.],
#              [1.],
#              [1.],
#              [1.],
#              [1.]])

Y = np.array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

layered_backward_propagation(AL, Y, caches)


3
L is :  2
sigmoid dZ:  tf.Tensor(
[[-8.00059941]
 [-7.99963136]
 [-7.9975372 ]
 [-7.99654555]
 [-8.00138527]
 [-8.00047209]
 [-7.99847274]
 [-8.00170341]
 [-8.00013238]
 [-8.00044623]], shape=(10, 1), dtype=float64)
sigmoid dZ:  tf.Tensor(
[[-0.12844599]
 [ 0.6904823 ]
 [-1.1031659 ]
 [ 0.34281303]
 [-1.1549548 ]
 [ 0.17256866]
 [-0.08093373]
 [-1.20325212]
 [-0.35836319]
 [-2.0654111 ]], shape=(10, 1), dtype=float64)


{'dA1': <tf.Tensor: shape=(10, 1), dtype=float64, numpy=
 array([[-0.03209398],
        [ 0.17260152],
        [-0.27578673],
        [ 0.08563949],
        [-0.2887243 ],
        [ 0.04313725],
        [-0.02021397],
        [-0.30039557],
        [-0.08957655],
        [-0.51633772]])>,
 'dW2': <tf.Tensor: shape=(10, 10), dtype=float64, numpy=
 array([[-0.37384838,  0.        ,  0.        ,  0.        ,  0.        ,
         -0.17084017,  0.        ,  0.        ,  0.        , -0.08641027],
        [-0.37380314,  0.        ,  0.        ,  0.        ,  0.        ,
         -0.1708195 ,  0.        ,  0.        ,  0.        , -0.08639981],
        [-0.37370529,  0.        ,  0.        ,  0.        ,  0.        ,
         -0.17077479,  0.        ,  0.        ,  0.        , -0.08637719],
        [-0.37365895,  0.        ,  0.        ,  0.        ,  0.        ,
         -0.17075361,  0.        ,  0.        ,  0.        , -0.08636648],
        [-0.3738851 ,  0.        ,  0.        ,  0.     

In [103]:
# Update parameters.
def update_parameters(parameters, grads, learning_rate=0.01):
    L = len(paramters) // 2
    
    for l in range(L):
        parameters["W" + str(l + 1)] = parameters["W" + str(l + 1)] - learning_rate * grads["dW" + str(l + 1)]
        parameters["b" + str(l + 1)] = parameters["b" + str(l + 1)] - learning_rate * grads["db" + str(l + 1)]